spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopflow_users_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080
  servlet:
    context-path: /api
jwt:
  secret: shopflow-auth-service-secret-key-2024-seguro
  expiration: 3600000 # 1 hour in milliseconds